# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ShenhuStockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShenhuStockWindow(object):
    def setupUi(self, ShenhuStockWindow):
        ShenhuStockWindow.setObjectName("ShenhuStockWindow")
        ShenhuStockWindow.resize(1500, 870)
        ShenhuStockWindow.setMinimumSize(QtCore.QSize(1500, 870))
        ShenhuStockWindow.setMaximumSize(QtCore.QSize(1500, 870))
        self.ScrollArea = QtWidgets.QScrollArea(ShenhuStockWindow)
        self.ScrollArea.setGeometry(QtCore.QRect(259, 30, 600, 841))
        self.ScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.ScrollContentWidget = QtWidgets.QWidget()
        self.ScrollContentWidget.setGeometry(QtCore.QRect(0, 0, 1180, 824))
        self.ScrollContentWidget.setMinimumSize(QtCore.QSize(1180, 100))
        self.ScrollContentWidget.setMaximumSize(QtCore.QSize(1180, 16777215))
        self.ScrollContentWidget.setObjectName("ScrollContentWidget")
        self.ScrollArea.setWidget(self.ScrollContentWidget)
        self.TopLeftWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.TopLeftWidget.setGeometry(QtCore.QRect(0, 0, 261, 30))
        self.TopLeftWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.TopLeftWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.TopLeftWidget.setObjectName("TopLeftWidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.TopLeftWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 262, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OrderLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.OrderLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.OrderLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OrderLabel.setFont(font)
        self.OrderLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.OrderLabel.setStyleSheet("color: rgb(168, 168, 168);")
        self.OrderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OrderLabel.setObjectName("OrderLabel")
        self.horizontalLayout_2.addWidget(self.OrderLabel)
        self.SymbolButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.SymbolButton.setMinimumSize(QtCore.QSize(90, 30))
        self.SymbolButton.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SymbolButton.setFont(font)
        self.SymbolButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.SymbolButton.setObjectName("SymbolButton")
        self.horizontalLayout_2.addWidget(self.SymbolButton)
        self.NameButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.NameButton.setMinimumSize(QtCore.QSize(120, 30))
        self.NameButton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NameButton.setFont(font)
        self.NameButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.NameButton.setObjectName("NameButton")
        self.horizontalLayout_2.addWidget(self.NameButton)
        self.LeftWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.LeftWidget.setGeometry(QtCore.QRect(50, 30, 210, 825))
        self.LeftWidget.setObjectName("LeftWidget")
        self.LeftContentWidget = QtWidgets.QWidget(self.LeftWidget)
        self.LeftContentWidget.setGeometry(QtCore.QRect(0, 0, 210, 80))
        self.LeftContentWidget.setObjectName("LeftContentWidget")
        self.label_2 = QtWidgets.QLabel(ShenhuStockWindow)
        self.label_2.setGeometry(QtCore.QRect(0, 854, 260, 16))
        self.label_2.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.OrderWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.OrderWidget.setGeometry(QtCore.QRect(0, 30, 50, 825))
        self.OrderWidget.setObjectName("OrderWidget")
        self.OrderContentWidget = QtWidgets.QWidget(self.OrderWidget)
        self.OrderContentWidget.setGeometry(QtCore.QRect(0, 0, 50, 80))
        self.OrderContentWidget.setObjectName("OrderContentWidget")
        self.TopMiddleWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.TopMiddleWidget.setGeometry(QtCore.QRect(260, 0, 600, 30))
        self.TopMiddleWidget.setObjectName("TopMiddleWidget")
        self.ParamWidget = QtWidgets.QWidget(self.TopMiddleWidget)
        self.ParamWidget.setGeometry(QtCore.QRect(0, 0, 1180, 30))
        self.ParamWidget.setObjectName("ParamWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.ParamWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1182, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TotalMVButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.TotalMVButton.setMinimumSize(QtCore.QSize(100, 30))
        self.TotalMVButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TotalMVButton.setFont(font)
        self.TotalMVButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.TotalMVButton.setObjectName("TotalMVButton")
        self.horizontalLayout.addWidget(self.TotalMVButton)
        self.TotalShareButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.TotalShareButton.setMinimumSize(QtCore.QSize(100, 30))
        self.TotalShareButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TotalShareButton.setFont(font)
        self.TotalShareButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.TotalShareButton.setObjectName("TotalShareButton")
        self.horizontalLayout.addWidget(self.TotalShareButton)
        self.CloseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CloseButton.setMinimumSize(QtCore.QSize(60, 30))
        self.CloseButton.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CloseButton.setFont(font)
        self.CloseButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.CloseButton.setObjectName("CloseButton")
        self.horizontalLayout.addWidget(self.CloseButton)
        self.TurnOverRateButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.TurnOverRateButton.setMinimumSize(QtCore.QSize(60, 30))
        self.TurnOverRateButton.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TurnOverRateButton.setFont(font)
        self.TurnOverRateButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.TurnOverRateButton.setObjectName("TurnOverRateButton")
        self.horizontalLayout.addWidget(self.TurnOverRateButton)
        self.VolumeRatioButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.VolumeRatioButton.setMinimumSize(QtCore.QSize(60, 30))
        self.VolumeRatioButton.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.VolumeRatioButton.setFont(font)
        self.VolumeRatioButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.VolumeRatioButton.setObjectName("VolumeRatioButton")
        self.horizontalLayout.addWidget(self.VolumeRatioButton)
        self.IndustryButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.IndustryButton.setMinimumSize(QtCore.QSize(100, 30))
        self.IndustryButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IndustryButton.setFont(font)
        self.IndustryButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.IndustryButton.setObjectName("IndustryButton")
        self.horizontalLayout.addWidget(self.IndustryButton)
        self.PEButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PEButton.setMinimumSize(QtCore.QSize(80, 30))
        self.PEButton.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PEButton.setFont(font)
        self.PEButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PEButton.setObjectName("PEButton")
        self.horizontalLayout.addWidget(self.PEButton)
        self.PETTMButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PETTMButton.setMinimumSize(QtCore.QSize(80, 30))
        self.PETTMButton.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PETTMButton.setFont(font)
        self.PETTMButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PETTMButton.setObjectName("PETTMButton")
        self.horizontalLayout.addWidget(self.PETTMButton)
        self.PBButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PBButton.setMinimumSize(QtCore.QSize(80, 30))
        self.PBButton.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PBButton.setFont(font)
        self.PBButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PBButton.setObjectName("PBButton")
        self.horizontalLayout.addWidget(self.PBButton)
        self.PSButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PSButton.setMinimumSize(QtCore.QSize(80, 30))
        self.PSButton.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSButton.setFont(font)
        self.PSButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PSButton.setObjectName("PSButton")
        self.horizontalLayout.addWidget(self.PSButton)
        self.PSTTMButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PSTTMButton.setMinimumSize(QtCore.QSize(80, 30))
        self.PSTTMButton.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSTTMButton.setFont(font)
        self.PSTTMButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PSTTMButton.setObjectName("PSTTMButton")
        self.horizontalLayout.addWidget(self.PSTTMButton)
        self.CircMvButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CircMvButton.setMinimumSize(QtCore.QSize(100, 30))
        self.CircMvButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CircMvButton.setFont(font)
        self.CircMvButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.CircMvButton.setObjectName("CircMvButton")
        self.horizontalLayout.addWidget(self.CircMvButton)
        self.FloatShareButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.FloatShareButton.setMinimumSize(QtCore.QSize(100, 30))
        self.FloatShareButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FloatShareButton.setFont(font)
        self.FloatShareButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.FloatShareButton.setObjectName("FloatShareButton")
        self.horizontalLayout.addWidget(self.FloatShareButton)
        self.FreeShareButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.FreeShareButton.setMinimumSize(QtCore.QSize(100, 30))
        self.FreeShareButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FreeShareButton.setFont(font)
        self.FreeShareButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.FreeShareButton.setObjectName("FreeShareButton")
        self.horizontalLayout.addWidget(self.FreeShareButton)

        self.retranslateUi(ShenhuStockWindow)
        QtCore.QMetaObject.connectSlotsByName(ShenhuStockWindow)

    def retranslateUi(self, ShenhuStockWindow):
        _translate = QtCore.QCoreApplication.translate
        ShenhuStockWindow.setWindowTitle(_translate("ShenhuStockWindow", "Form"))
        self.OrderLabel.setText(_translate("ShenhuStockWindow", "序"))
        self.SymbolButton.setText(_translate("ShenhuStockWindow", "代码"))
        self.NameButton.setText(_translate("ShenhuStockWindow", "名称"))
        self.TotalMVButton.setText(_translate("ShenhuStockWindow", "总市值"))
        self.TotalShareButton.setText(_translate("ShenhuStockWindow", "总股本"))
        self.CloseButton.setText(_translate("ShenhuStockWindow", "收盘"))
        self.TurnOverRateButton.setText(_translate("ShenhuStockWindow", "换手%"))
        self.VolumeRatioButton.setText(_translate("ShenhuStockWindow", "量比"))
        self.IndustryButton.setText(_translate("ShenhuStockWindow", "所属行业"))
        self.PEButton.setText(_translate("ShenhuStockWindow", "市盈率"))
        self.PETTMButton.setText(_translate("ShenhuStockWindow", "市盈率TTM"))
        self.PBButton.setText(_translate("ShenhuStockWindow", "市净率"))
        self.PSButton.setText(_translate("ShenhuStockWindow", "市销率"))
        self.PSTTMButton.setText(_translate("ShenhuStockWindow", "市销率TTM"))
        self.CircMvButton.setText(_translate("ShenhuStockWindow", "流通市值"))
        self.FloatShareButton.setText(_translate("ShenhuStockWindow", "流通股本"))
        self.FreeShareButton.setText(_translate("ShenhuStockWindow", "自由流通股本"))


