# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ShenhuStockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShenhuStockWindow(object):
    def setupUi(self, ShenhuStockWindow):
        ShenhuStockWindow.setObjectName("ShenhuStockWindow")
        ShenhuStockWindow.resize(1500, 870)
        ShenhuStockWindow.setMinimumSize(QtCore.QSize(1500, 870))
        ShenhuStockWindow.setMaximumSize(QtCore.QSize(1500, 870))
        self.TopLeftWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.TopLeftWidget.setGeometry(QtCore.QRect(0, 0, 261, 30))
        self.TopLeftWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.TopLeftWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.TopLeftWidget.setObjectName("TopLeftWidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.TopLeftWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 262, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OrderParamLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.OrderParamLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.OrderParamLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OrderParamLabel.setFont(font)
        self.OrderParamLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.OrderParamLabel.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.OrderParamLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OrderParamLabel.setObjectName("OrderParamLabel")
        self.horizontalLayout_2.addWidget(self.OrderParamLabel)
        self.SymbolButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.SymbolButton.setMinimumSize(QtCore.QSize(90, 30))
        self.SymbolButton.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SymbolButton.setFont(font)
        self.SymbolButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.SymbolButton.setObjectName("SymbolButton")
        self.horizontalLayout_2.addWidget(self.SymbolButton)
        self.NameButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.NameButton.setMinimumSize(QtCore.QSize(120, 30))
        self.NameButton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NameButton.setFont(font)
        self.NameButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.NameButton.setObjectName("NameButton")
        self.horizontalLayout_2.addWidget(self.NameButton)
        self.LeftWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.LeftWidget.setGeometry(QtCore.QRect(0, 30, 260, 825))
        self.LeftWidget.setObjectName("LeftWidget")
        self.LeftContentWidget = QtWidgets.QWidget(self.LeftWidget)
        self.LeftContentWidget.setGeometry(QtCore.QRect(0, 0, 260, 80))
        self.LeftContentWidget.setObjectName("LeftContentWidget")
        self.TopMiddleWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.TopMiddleWidget.setGeometry(QtCore.QRect(260, 0, 600, 30))
        self.TopMiddleWidget.setObjectName("TopMiddleWidget")
        self.ParamWidget = QtWidgets.QWidget(self.TopMiddleWidget)
        self.ParamWidget.setGeometry(QtCore.QRect(0, 0, 1180, 30))
        self.ParamWidget.setObjectName("ParamWidget")
        self.PBButton = QtWidgets.QPushButton(self.ParamWidget)
        self.PBButton.setGeometry(QtCore.QRect(640, 0, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PBButton.setFont(font)
        self.PBButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PBButton.setObjectName("PBButton")
        self.VolumeRatioButton = QtWidgets.QPushButton(self.ParamWidget)
        self.VolumeRatioButton.setGeometry(QtCore.QRect(320, 0, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.VolumeRatioButton.setFont(font)
        self.VolumeRatioButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.VolumeRatioButton.setObjectName("VolumeRatioButton")
        self.PSTTMButton = QtWidgets.QPushButton(self.ParamWidget)
        self.PSTTMButton.setGeometry(QtCore.QRect(800, 0, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSTTMButton.setFont(font)
        self.PSTTMButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PSTTMButton.setObjectName("PSTTMButton")
        self.CloseButton = QtWidgets.QPushButton(self.ParamWidget)
        self.CloseButton.setGeometry(QtCore.QRect(200, 0, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CloseButton.setFont(font)
        self.CloseButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.CloseButton.setObjectName("CloseButton")
        self.PETTMButton = QtWidgets.QPushButton(self.ParamWidget)
        self.PETTMButton.setGeometry(QtCore.QRect(560, 0, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PETTMButton.setFont(font)
        self.PETTMButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PETTMButton.setObjectName("PETTMButton")
        self.FloatShareButton = QtWidgets.QPushButton(self.ParamWidget)
        self.FloatShareButton.setGeometry(QtCore.QRect(980, 0, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FloatShareButton.setFont(font)
        self.FloatShareButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.FloatShareButton.setObjectName("FloatShareButton")
        self.TurnOverRateButton = QtWidgets.QPushButton(self.ParamWidget)
        self.TurnOverRateButton.setGeometry(QtCore.QRect(260, 0, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TurnOverRateButton.setFont(font)
        self.TurnOverRateButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.TurnOverRateButton.setObjectName("TurnOverRateButton")
        self.IndustryButton = QtWidgets.QPushButton(self.ParamWidget)
        self.IndustryButton.setGeometry(QtCore.QRect(380, 0, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IndustryButton.setFont(font)
        self.IndustryButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.IndustryButton.setObjectName("IndustryButton")
        self.TotalMVButton = QtWidgets.QPushButton(self.ParamWidget)
        self.TotalMVButton.setGeometry(QtCore.QRect(0, 0, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TotalMVButton.setFont(font)
        self.TotalMVButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.TotalMVButton.setObjectName("TotalMVButton")
        self.PSButton = QtWidgets.QPushButton(self.ParamWidget)
        self.PSButton.setGeometry(QtCore.QRect(720, 0, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSButton.setFont(font)
        self.PSButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PSButton.setObjectName("PSButton")
        self.FreeShareButton = QtWidgets.QPushButton(self.ParamWidget)
        self.FreeShareButton.setGeometry(QtCore.QRect(1080, 0, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FreeShareButton.setFont(font)
        self.FreeShareButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.FreeShareButton.setObjectName("FreeShareButton")
        self.TotalShareButton = QtWidgets.QPushButton(self.ParamWidget)
        self.TotalShareButton.setGeometry(QtCore.QRect(100, 0, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TotalShareButton.setFont(font)
        self.TotalShareButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.TotalShareButton.setObjectName("TotalShareButton")
        self.PEButton = QtWidgets.QPushButton(self.ParamWidget)
        self.PEButton.setGeometry(QtCore.QRect(480, 0, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PEButton.setFont(font)
        self.PEButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.PEButton.setObjectName("PEButton")
        self.CircMVButton = QtWidgets.QPushButton(self.ParamWidget)
        self.CircMVButton.setGeometry(QtCore.QRect(880, 0, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CircMVButton.setFont(font)
        self.CircMVButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(168, 168, 168);")
        self.CircMVButton.setObjectName("CircMVButton")
        self.MiddleWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.MiddleWidget.setGeometry(QtCore.QRect(260, 30, 600, 825))
        self.MiddleWidget.setObjectName("MiddleWidget")
        self.StockWidget = QtWidgets.QWidget(self.MiddleWidget)
        self.StockWidget.setGeometry(QtCore.QRect(0, 0, 120, 80))
        self.StockWidget.setObjectName("StockWidget")
        self.HorScrollBar = QtWidgets.QScrollBar(ShenhuStockWindow)
        self.HorScrollBar.setGeometry(QtCore.QRect(0, 855, 860, 15))
        self.HorScrollBar.setMaximum(49)
        self.HorScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.HorScrollBar.setObjectName("HorScrollBar")
        self.VerScrollBar = QtWidgets.QScrollBar(ShenhuStockWindow)
        self.VerScrollBar.setGeometry(QtCore.QRect(860, 0, 15, 870))
        self.VerScrollBar.setMaximum(999)
        self.VerScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.VerScrollBar.setObjectName("VerScrollBar")
        self.StockNameLabel = QtWidgets.QLabel(ShenhuStockWindow)
        self.StockNameLabel.setGeometry(QtCore.QRect(880, 0, 631, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.StockNameLabel.setFont(font)
        self.StockNameLabel.setStyleSheet("color: rgb(255, 170, 0);")
        self.StockNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StockNameLabel.setObjectName("StockNameLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(ShenhuStockWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(879, 49, 621, 821))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.RenderLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.RenderLayout.setContentsMargins(0, 0, 0, 0)
        self.RenderLayout.setSpacing(0)
        self.RenderLayout.setObjectName("RenderLayout")

        self.retranslateUi(ShenhuStockWindow)
        QtCore.QMetaObject.connectSlotsByName(ShenhuStockWindow)

    def retranslateUi(self, ShenhuStockWindow):
        _translate = QtCore.QCoreApplication.translate
        ShenhuStockWindow.setWindowTitle(_translate("ShenhuStockWindow", "Form"))
        self.OrderParamLabel.setText(_translate("ShenhuStockWindow", "序"))
        self.SymbolButton.setText(_translate("ShenhuStockWindow", "代码"))
        self.NameButton.setText(_translate("ShenhuStockWindow", "名称"))
        self.PBButton.setText(_translate("ShenhuStockWindow", "市净率"))
        self.VolumeRatioButton.setText(_translate("ShenhuStockWindow", "量比"))
        self.PSTTMButton.setText(_translate("ShenhuStockWindow", "市销率TTM"))
        self.CloseButton.setText(_translate("ShenhuStockWindow", "收盘"))
        self.PETTMButton.setText(_translate("ShenhuStockWindow", "市盈率TTM"))
        self.FloatShareButton.setText(_translate("ShenhuStockWindow", "流通股本"))
        self.TurnOverRateButton.setText(_translate("ShenhuStockWindow", "换手%"))
        self.IndustryButton.setText(_translate("ShenhuStockWindow", "所属行业"))
        self.TotalMVButton.setText(_translate("ShenhuStockWindow", "总市值"))
        self.PSButton.setText(_translate("ShenhuStockWindow", "市销率"))
        self.FreeShareButton.setText(_translate("ShenhuStockWindow", "自由流通股本"))
        self.TotalShareButton.setText(_translate("ShenhuStockWindow", "总股本"))
        self.PEButton.setText(_translate("ShenhuStockWindow", "市盈率"))
        self.CircMVButton.setText(_translate("ShenhuStockWindow", "流通市值"))
        self.StockNameLabel.setText(_translate("ShenhuStockWindow", "平安银行"))


